const data = {
  products: [
    {
      name: 'Free Shirt',
      category: 'shirts',
      image: '/images/shirt1.jpeg',
      price: 70,
      brand: 'Top-drawer',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A beautiful shirt',
    },
    {
      name: 'Fit Shirt',
      category: 'shirts',
      image: '/images/shirt2.jpeg',
      price: 80,
      brand: 'Top-drawer',
      rating: 4.5,
      numReviews: 10,
      countInStock: 30,
      description: 'A beautiful shirt',
    },
    {
      name: 'Long Shirt',
      category: 'shirts',
      image: '/images/shirt3.jpeg',
      price: 90,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 40,
      description: 'A beautiful shirt',
    },
    {
      name: 'Free  Pant',
      category: 'pants',
      image: '/images/pant1.jpeg',
      price: 100,
      brand: 'Adiddas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 50,
      description: 'Smart looking pants',
    },
    {
      name: 'Slim pants',
      category: 'pants',
      image: '/images/pant2.jpeg',
      price: 120,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 60,
      description: 'Smart looking pants',
    },
    {
      name: 'Free  Pant',
      category: 'pants',
      image: '/images/pant1.jpeg',
      price: 100,
      brand: 'Adiddas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 50,
      description: 'Smart looking pants',
    },
  ],
};

export default data;
